name: Test
on:
  release:
    types: [published]
  workflow_dispatch:
  repository_dispatch:
    types: [release-published]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        env:
          FEBIO_URL: ${{ secrets.FEBIO_URL }}
        run: |
          curl -L "$FEBIO_URL" --output FEBio4.tar.gz
          tar -xvf FEBio4.tar.gz
          echo "$GITHUB_WORKSPACE/FEBio4/bin/" >> $GITHUB_PATH
          pip install pytest
          pip install .

      - name: Test and Coverage
        run: python -m pytest
